Replace sass with sassc-rails
sass-ruby has reached end of life and sassc-rails is recommended
migration.
Technically, sprockets 3 doesn't support sassc and has implicit
dependency on sass (ruby), hence the following error on precompilation::
```
LoadError: cannot load such file -- sass
/home/aditya/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in
`require'
/home/aditya/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in
`block in require'
/home/aditya/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in
`load_dependency'
/home/aditya/.rvm/gems/ruby-2.5.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in
`require'
/home/aditya/.rvm/gems/ruby-2.5.3/gems/sprockets-3.7.2/lib/sprockets/autoload/sass.rb:1:in
`<top (required)>'
```
We need to add `require 'sassc-rails'` to fix this.